"""Type stubs for the _quote C extension."""

sqlite_version: str
max_input_bytes: int

def quote_identifier(name: str, /) -> str: ...
def quote_string(value: str | None, /) -> str: ...
def quote_string_bare(value: str, /) -> str: ...
